name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubunt-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: ./script.sh